name: "build it!"

on:
  push:
    branches:
      - mrk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          node-version: '20'
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: yarn install
      - run: yarn build
      - run: rm -r .git
      - run: git clone git@github.com:abacef/abacef.github.io.git
      - run: cd "abacef.github.io"
      - run: ls -l
      - run: git branch
      - run: rm -r .
      - run: cp -r ../build/* .
      - run: git config --global user.email "not_an_email_address@abacef.github.io"
      - run: git config --global user.name "Juice Brenner bot"
      - run: git add --all && git commit -m "yet another automated commit from tetrageist/WeatherApp"
      - run: git push

